import express, { Request, Response } from "express";
import { PORT } from "./utils/constants";
import cors from "cors";
import morgan from "morgan";

/**
 * DO NOT EDIT THIS FILE
 * ! Add logic in app.ts only
 */
import "./app";

//Controllers
import { testRouter } from "components/testApi/testRouters";

const app = express();

//Middleware
app.use(cors());
app.use(morgan("dev")); // To check HTTP request logger middleware for node.js
app.use(express.json()); // Parse requests of content-type - application/json

//Router config
app.use(testRouter);

//Index Router
app.get("/", (_req: Request, res: Response) => {
  res.status(200).send(`
    <h1 style="font-family: cursive;text-align: center;">Server film is running<h1>`);
});

app.listen(PORT, () => {
  console.log(`\
  🚀 Server ready at: http://localhost:4000
  ⭐️ Check it out!!!
`);
});
